/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.DocGiaDAO;
import dao.PhieuMuonSachDAO;
import dao.SachDAO;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PhieuMuonSach;
import model.TaiKhoan;
import util.ChuanHoa;
import util.EmailSender;
import util.NgayThangNam;

/**
 *
 * @author admin
 */
public class Borrow extends javax.swing.JFrame {
    TaiKhoan acc;
    /**
     * Creates new form Borrow
     */
    public Borrow() {
        initComponents();
        setLocationRelativeTo(null);
        Image img = new ImageIcon(this.getClass().getResource("/icon/library3.png")).getImage();
        this.setIconImage(img);
    }
    
    public Borrow(TaiKhoan taiKhoan) {
        initComponents();
        setLocationRelativeTo(null);
        Image img = new ImageIcon(this.getClass().getResource("/icon/library3.png")).getImage();
        this.setIconImage(img);
        labelUsername.setText(taiKhoan.getTenDangNhap());
        acc = taiKhoan;
    }
    
    public void showTongSoDocGiaMuonSach() {
        String s = "";
        s += new PhieuMuonSachDAO().getSoLuongDocGiaMuonSach();
        labelSoDocGia.setText(s);
    }
    
    public void showTongSoPhieuMuonChoDuyet() {
        String s = "";
        s += new PhieuMuonSachDAO().getSoLuongPhieuChoPheDuyet();
        labelSoLuongPhieuChoDuyet.setText(s);
    }
    
    public void showTable() {
        tableMain.removeAll();
        DefaultTableModel model = new PhieuMuonSachDAO().getListPhieu();
        tableMain.setModel(model);
    }
    
    public void showTablePhu() {
        tablePhu.removeAll();
        DefaultTableModel model = new PhieuMuonSachDAO().getListPending();
        tablePhu.setModel(model);
    }
    
    public void sendEmailAccept(String email, String tenSach) { 
        new Thread(() -> {
            try {
                EmailSender.sendEmailAfterAccept(email, tenSach);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
    }
    
    public void sendEmailReject(String email, String tenSach) { 
        new Thread(() -> {
            try {
                EmailSender.sendEmailAfterReject(email, tenSach);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMain = new javax.swing.JTable();
        btnNhapPhieuMuon = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnTraSach = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        labelSoDocGia = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePhu = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnChapNhan = new javax.swing.JButton();
        btnTuChoi = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelSoLuongPhieuChoDuyet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MƯỢN SÁCH");
        setLocationByPlatform(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/borrow.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("CHI TIẾT MƯỢN SÁCH");

        tableMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableMain.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tableMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã mượn", "Mã ĐG", "Mã sách", "Họ tên", "Tên sách", "Ngày mượn", "Ngày hẹn trả", "Ngày trả thực tế", "Số lượng", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableMain.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tableMainComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tableMain);

        btnNhapPhieuMuon.setBackground(new java.awt.Color(204, 204, 255));
        btnNhapPhieuMuon.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNhapPhieuMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnNhapPhieuMuon.setText("NHẬP PHIẾU MƯỢN SÁCH");
        btnNhapPhieuMuon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapPhieuMuonActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(204, 204, 255));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout (1).png"))); // NOI18N
        btnExit.setText("THOÁT");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("Tổng số độc giả mượn sách:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("độc giả");

        btnTraSach.setBackground(new java.awt.Color(204, 204, 255));
        btnTraSach.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnTraSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/borrow (1).png"))); // NOI18N
        btnTraSach.setText("TRẢ SÁCH");
        btnTraSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraSachActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 255));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/remove.png"))); // NOI18N
        btnDelete.setText("XOÁ");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        labelSoDocGia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelSoDocGia.setText("-1");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Xin chào, ");

        labelUsername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelUsername.setText("N/A");
        labelUsername.setToolTipText("");
        labelUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tablePhu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablePhu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tablePhu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestID", "Mã ĐG", "Mã sách", "Họ tên", "Tên sách", "Ngày yêu cầu", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePhu.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tablePhuComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(tablePhu);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("DANH SÁCH PHIẾU MƯỢN CHỜ PHÊ DUYỆT");

        btnChapNhan.setBackground(new java.awt.Color(204, 204, 255));
        btnChapNhan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnChapNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/accept.png"))); // NOI18N
        btnChapNhan.setText("CHẤP NHẬN");
        btnChapNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChapNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChapNhanActionPerformed(evt);
            }
        });

        btnTuChoi.setBackground(new java.awt.Color(204, 204, 255));
        btnTuChoi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnTuChoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/remove.png"))); // NOI18N
        btnTuChoi.setText("TỪ CHỐI");
        btnTuChoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTuChoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuChoiActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("Tổng số phiếu chờ phê duyệt:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("độc giả");

        labelSoLuongPhieuChoDuyet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelSoLuongPhieuChoDuyet.setText("-1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUsername))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(125, 125, 125))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnChapNhan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTuChoi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelSoLuongPhieuChoDuyet)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNhapPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTraSach)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addGap(160, 160, 160)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSoDocGia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(labelUsername))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(labelSoDocGia)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNhapPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(labelSoLuongPhieuChoDuyet)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChapNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTuChoi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        if(acc.getVaiTro().equals("Admin")) {
            Home home = new Home(acc);
            home.setVisible(true);
            home.setLocationRelativeTo(null);
            this.setVisible(false);
        }
        else if(acc.getVaiTro().equals("Thủ thư")) {
            HomeOfLibrarian home = new HomeOfLibrarian(acc);
            home.setVisible(true);
            home.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if(acc.getVaiTro().equals("Admin")) {
            Home home = new Home(acc);
            home.setVisible(true);
            home.setLocationRelativeTo(null);
            this.setVisible(false);
        }
        else if(acc.getVaiTro().equals("Thủ thư")) {
            HomeOfLibrarian home = new HomeOfLibrarian(acc);
            home.setVisible(true);
            home.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_formWindowClosed

    private void btnNhapPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapPhieuMuonActionPerformed
        // TODO add your handling code here:
        NhapPhieuMuonSach phieu = new NhapPhieuMuonSach(acc);
        phieu.setVisible(true);
        phieu.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnNhapPhieuMuonActionPerformed

    private void tableMainComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableMainComponentShown
        // TODO add your handling code here:
        showTable();
        showTongSoDocGiaMuonSach();
    }//GEN-LAST:event_tableMainComponentShown

    private void btnTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraSachActionPerformed
        // TODO add your handling code here:
        int possition = tableMain.getSelectedRow();
        String maMuon = tableMain.getModel().getValueAt(possition, 0).toString();
        int ma = Integer.parseInt(maMuon);
        PhieuMuonSachDAO phieuMuon = new PhieuMuonSachDAO();
        phieuMuon.traSach(ma);
        JOptionPane.showMessageDialog(this, "Trả thành công !");
        showTable();
        showTongSoDocGiaMuonSach();
    }//GEN-LAST:event_btnTraSachActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        showTable();
        showTongSoDocGiaMuonSach();
        showTablePhu();
        showTongSoPhieuMuonChoDuyet();
    }//GEN-LAST:event_formComponentShown

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int possition = tableMain.getSelectedRow();
        String maMuon = tableMain.getModel().getValueAt(possition, 0).toString();
        int ma = Integer.parseInt(maMuon);
        String tinhTrang = tableMain.getModel().getValueAt(possition, 9).toString();
        if(tinhTrang.equals("Đã trả")) {
            PhieuMuonSachDAO phieuMuonDAO = new PhieuMuonSachDAO();
            phieuMuonDAO.deletePhieuMuonSach(ma);
            JOptionPane.showMessageDialog(this, "Xoá thành công !");
        }
        else
            JOptionPane.showMessageDialog(this, "Lỗi, vui lòng thử lại !");
        showTable();
        showTongSoDocGiaMuonSach();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tablePhuComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tablePhuComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePhuComponentShown

    private void btnChapNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChapNhanActionPerformed
        // TODO add your handling code here:
        int possition = tablePhu.getSelectedRow();
        int requestID = (int)tablePhu.getModel().getValueAt(possition, 0);
        String maDG = tablePhu.getModel().getValueAt(possition, 1).toString();
        String maSach = tablePhu.getModel().getValueAt(possition, 2).toString();
        String ngayMuon = NgayThangNam.getBorrowDate();
        String ngayMuon_ChuanHoa = ChuanHoa.chuanHoaNgayThang(NgayThangNam.getBorrowDate());
        String ngayHenTra = ChuanHoa.chuanHoaNgayThang(NgayThangNam.getReturnDate(ngayMuon));
        int soLuong = 1, tinhTrang = 1;
        String tenSach = new PhieuMuonSachDAO().timtenSach(maSach);
        String email = new DocGiaDAO().thongTinCaNhan(maDG).getEmail();
        
        PhieuMuonSach phieuMuon = new PhieuMuonSach(maDG, maSach, ngayMuon_ChuanHoa, soLuong, tinhTrang, requestID, ngayHenTra);
        PhieuMuonSachDAO phieuMuonDAO = new PhieuMuonSachDAO();
        if(phieuMuonDAO.addRequestPhieuMuonSach(phieuMuon)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công !");
            showTable();
            showTablePhu();
            showTongSoDocGiaMuonSach();
            showTongSoPhieuMuonChoDuyet();
            sendEmailAccept(email, tenSach);
        }
        else {
            JOptionPane.showMessageDialog(this, "Lỗi, vui lòng thử lại !");
        }
            
    }//GEN-LAST:event_btnChapNhanActionPerformed

    private void btnTuChoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuChoiActionPerformed
        // TODO add your handling code here:
        int possition = tablePhu.getSelectedRow();
        int requestID = (int)tablePhu.getModel().getValueAt(possition, 0);
        String maDG = tablePhu.getModel().getValueAt(possition, 1).toString();
        String maSach = tablePhu.getModel().getValueAt(possition, 2).toString();
        String tenSach = new PhieuMuonSachDAO().timtenSach(maSach);
        String email = new DocGiaDAO().thongTinCaNhan(maDG).getEmail();
        PhieuMuonSachDAO phieuMuonSachDAO = new PhieuMuonSachDAO();
        phieuMuonSachDAO.tuChoiPhieuMuon(requestID);
        JOptionPane.showMessageDialog(this, "Từ chối thành công !");
        showTablePhu();
        showTongSoPhieuMuonChoDuyet();
        sendEmailReject(email, tenSach);
    }//GEN-LAST:event_btnTuChoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChapNhan;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNhapPhieuMuon;
    private javax.swing.JButton btnTraSach;
    private javax.swing.JButton btnTuChoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelSoDocGia;
    private javax.swing.JLabel labelSoLuongPhieuChoDuyet;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JTable tableMain;
    private javax.swing.JTable tablePhu;
    // End of variables declaration//GEN-END:variables
}
